ACTIVATE_BOT = "Activate the bot using /start command"
WELCOME = (
    "I will help you manage your shopping list. Here are commands you can use:\n\n"
    "/help - Display help information\n"
    "/add - Use this command to add products to the list. "
    "Products need to be separated by comma, e.g:\n\n"
    "<code>/add 🍏 Apple, 🍅 Tomato, 🍗 0.5kg of meat</code>\n\n"
    "/list - Display shopping list\n"
    "/edit - Edit shopping list. You can add or remove a products\n"
    "/clear - Clear list.\n"
)
NO = "❗️Opsss. NO!"
YES = "Yeah! Just do it!"
CONFIRM = "Are you sure you want to clear the shopping list?"
CLEAR = "The shopping list has been cleared."
EMPTY = "Your list is empty. Use /add command to add products"
WRONG = "Something went wrong! Please do not use special characters and try again."
MINUS = "➖"
PLUS = "➕"
REMOVE = "❌"
CLOSE = "🔚 Close"
REFRESH = "🔄 Refresh"
